### ISSUE TITLE
Spurious message to rename config files 

### ISSUE THREAD

**Issue by StevenCTimm** [HEPCloud/decisionengine#131]
Please rename '/etc/decisionengine/config.d/job_classification.jsonnet' to '/etc/decisionengine/config.d/job_classification.jsonnet'.
Please rename '/etc/decisionengine/decision_engine.conf' to '/etc/decisionengine/decision_engine.jsonnet'.
Please rename '/etc/decisionengine/config.d/AWS_Calculations_with_source_proxy.jsonnet' to '/etc/decisionengine/config.d/AWS_Calculations_with_source_proxy.jsonnet'.
Please rename '/etc/decisionengine/config.d/sample_gcebilling.jsonnet' to '/etc/decisionengine/config.d/sample_gcebilling.jsonnet'.
Please rename '/etc/decisionengine/config.d/Gce.jsonnet' to '/etc/decisionengine/config.d/Gce.jsonnet'.
Please rename '/etc/decisionengine/config.d/Nersc.jsonnet' to '/etc/decisionengine/config.d/Nersc.jsonnet'.
Please rename '/etc/decisionengine/config.d/channel_aws_config_data.jsonnet' to '/etc/decisionengine/config.d/channel_aws_config_data.jsonnet'.
Please rename '/etc/decisionengine/config.d/AWSbilling.jsonnet' to '/etc/decisionengine/config.d/AWSbilling.jsonnet'.
Please rename '/etc/decisionengine/config.d/resource_request.jsonnet' to '/etc/decisionengine/config.d/resource_request.jsonnet'.
2020-07-08 20:16:14,019 - decision_engine - ConfigManager - MainThread - ERROR - resource_request.jsonnet No module named 'glideinwms', REMOVING the channel
Please rename '/etc/decisionengine/config.d/job_classification.jsonnet' to '/etc/decisionengine/config.d/job_classification.jsonnet'.

The framework is telling me to rename all the files to *.jsonnet even though I have already done so.
Please fix that.

**Comment by knoepfel** [comment]
Well _that_'s annoying!  I'll take a look.

**Comment by knoepfel** [comment]
This issue has been fixed with PR #128.

**Comment by StevenCTimm** [comment]
showing pending_int_test label now, will hold open until integration test verifies it is done

**Comment by StevenCTimm** [comment]
Individual channels don't give this warning anymore in 1.3.0rc1  but the framework does.

Please rename '/etc/decisionengine/decision_engine.conf' to '/etc/decisionengine/decision_engine.jsonnet'.
(from startup.log)

It's doubly irritating because if you actually do rename the file to decision_engine.jsonnet then the framework can't find it.

This is still broken, it is a blocking issue to approval of this release.

**Comment by knoepfel** [comment]
@StevenCTimm, I stumbled across a similar problem a few days ago.  I will come up with a solution.  In the meantime, just keeping the name with the `.conf` extension should be fine, even though you will have a message in the log.

**Comment by knoepfel** [comment]
@StevenCTimm, can you send me/attach the decision_engine.jsonnet file you are trying to use?

**Comment by StevenCTimm** [comment]
drwxr-xr-x. 2 decisionengine decisionengine 4096 Jul 22 10:36 modules.conf
[root@fermicloud117 decisionengine]# cat decision_engine.jsonnet 
{
    "logger": {
	"log_file": "/var/log/decisionengine/decision_engine_log",
	"max_file_size": 200000000,
	"max_backup_count": 6,
	"log_level": "DEBUG",
        "global_channel_log_level": "DEBUG"
	},

    "channels": "/etc/decisionengine/config.d",

    "dataspace": {
	"reaper_start_delay_seconds": 1818,
	"retention_interval_in_days": 365,
	"datasource": {
	    "module": "decisionengine.framework.dataspace.datasources.postgresql",
	    "name": "Postgresql",
	    "config": {
		"user": "postgres",
		"blocking": true,
		"host": "localhost",
		"port": 5432,
		"database": "decisionengine",
		"maxconnections": 100,
		"maxcached": 10
		}
	    }
	}
}

**Comment by StevenCTimm** [comment]
It formatted sort of weird

**Comment by knoepfel** [comment]
Thanks.  That'll work.

**Comment by knoepfel** [comment]
@StevenCTimm, my proposed solution is for the framework to simply require that the name of the file be called `decision_engine.jsonnet`.  And that file must be a valid Jsonnet file.  Channel configuration files can still be Python-based as long as they are compatible with JSON.

Do you see any problem with this approach?

**Comment by StevenCTimm** [comment]
Sounds reasonable to me.

Steve

________________________________

**Comment by knoepfel** [comment]
See PR #135.

**Comment by StevenCTimm** [comment]
Fixed in 1.3.0, closing.
